version: "3.1"

services:

  nginx:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - .:/application
      - ./log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - 81:81
      - 82:82
      - 83:83
    depends_on:
      - php-fpm
    restart: always

  php-fpm:
    build:
      context: ./php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./php-fpm/php7.2.ini:/usr/local/etc/php/php7.2.ini
#      - /etc/localtime:/etc/localtime:ro
    expose:
      - "9000"
    extra_hosts:
      - "localhost:127.0.0.1"
    restart: always
